services:
  php:
    user: '${USER_ID}:${GROUP_ID}'
    build: ./docker/php
    volumes:
      - .:/var/www:delegated        
    depends_on:
      - database
    networks:
      - app_network                

  nginx:
    build: ./docker/nginx
    ports:
      - "8003:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - php
    networks:
      - app_network                

  database:
    image: mariadb:10.11.13
    environment:
      MARIADB_USER: admin
      MARIADB_ROOT_PASSWORD: Afpa1234
      MARIADB_PASSWORD: Afpa1234
      MARIADB_DATABASE: village_green
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'no'
    volumes:
      - village_green_db_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
    networks:
      - app_network                

  adminer:
    image: adminer:latest
    depends_on:
      - database
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8083:8080"               
    networks:
      - app_network               

  node:  
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - app_network

volumes:
  village_green_db_data:

networks:
  app_network:
